// store/constants/adminConstants.ts

export const CREATE_BU_REQUEST = "CREATE_BU_REQUEST";
export const CREATE_BU_SUCCESS = "CREATE_BU_SUCCESS";
export const CREATE_BU_FAILURE = "CREATE_BU_FAILURE";

export const GET_BU_REQUEST = "GET_BU_REQUEST";
export const GET_BU_SUCCESS = "GET_BU_SUCCESS";
export const GET_BU_FAILURE = "GET_BU_FAILURE";

export const ADMIN_DASHBOARD_REQUEST = "ADMIN_DASHBOARD_REQUEST";
export const ADMIN_DASHBOARD_SUCCESS = "ADMIN_DASHBOARD_SUCCESS";
export const ADMIN_DASHBOARD_FAIL = "ADMIN_DASHBOARD_FAIL";
