// store/constants/adminConstants.ts

export const CREATE_BU_REQUEST = "CREATE_BU_REQUEST";
export const CREATE_BU_SUCCESS = "CREATE_BU_SUCCESS";
export const CREATE_BU_FAILURE = "CREATE_BU_FAILURE";

export const GET_BU_REQUEST = "GET_BU_REQUEST";
export const GET_BU_SUCCESS = "GET_BU_SUCCESS";
export const GET_BU_FAILURE = "GET_BU_FAILURE";


export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";


export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";
