// store/constants/employeeConstants.ts

// CREATE / UPDATE EMPLOYEE
export const UPSERT_EMP_REQUEST = "UPSERT_EMP_REQUEST";
export const UPSERT_EMP_SUCCESS = "UPSERT_EMP_SUCCESS";
export const UPSERT_EMP_FAILURE = "UPSERT_EMP_FAILURE";

// GET ALL EMPLOYEES
export const GET_EMP_REQUEST = "GET_EMP_REQUEST";
export const GET_EMP_SUCCESS = "GET_EMP_SUCCESS";
export const GET_EMP_FAILURE = "GET_EMP_FAILURE";

// GET EMPLOYEE BY ID
export const GET_SINGLE_EMP_REQUEST = "GET_SINGLE_EMP_REQUEST";
export const GET_SINGLE_EMP_SUCCESS = "GET_SINGLE_EMP_SUCCESS";
export const GET_SINGLE_EMP_FAILURE = "GET_SINGLE_EMP_FAILURE";

// GET MANAGERS
export const GET_MANAGERS_REQUEST = "GET_MANAGERS_REQUEST";
export const GET_MANAGERS_SUCCESS = "GET_MANAGERS_SUCCESS";
export const GET_MANAGERS_FAILURE = "GET_MANAGERS_FAILURE";


// employeeConstants.ts

export const GET_CURRENT_EMP_REQUEST = "GET_CURRENT_EMP_REQUEST";
export const GET_CURRENT_EMP_SUCCESS = "GET_CURRENT_EMP_SUCCESS";
export const GET_CURRENT_EMP_FAILURE = "GET_CURRENT_EMP_FAILURE";
